"""Makes the installer's art from the FightCord logo (logo-source.png, the full-size artwork):
  logo.png       600 px, drawn in the setup window
  fightcord.ico  the exe icon: the whole logo at 48 px and up, just the mascot's head below that
Run once after changing the logo; the outputs are kept in the repo."""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
src = Image.open(os.path.join(HERE, 'logo-source.png')).convert('RGBA')
src = src.crop(src.getchannel('A').point(lambda a: 255 if a > 20 else 0).getbbox())


def square(img):
    s = max(img.size)
    out = Image.new('RGBA', (s, s), (0, 0, 0, 0))
    out.paste(img, ((s - img.width) // 2, (s - img.height) // 2), img)
    return out


full = square(src)
full.resize((600, 600), Image.LANCZOS).save(os.path.join(HERE, 'logo.png'), optimize=True)

# the head + fists sit in the upper-middle of the artwork
w, h = src.size
head = square(src.crop((int(w * 0.12), 0, int(w * 0.88), int(h * 0.58))))
frames = [full.resize((s, s), Image.LANCZOS) for s in (256, 128, 64, 48)] + \
         [head.resize((s, s), Image.LANCZOS) for s in (32, 24, 16)]
frames[0].save(os.path.join(HERE, 'fightcord.ico'), format='ICO', sizes=[f.size for f in frames], append_images=frames[1:])
full.resize((128, 128), Image.LANCZOS).save(os.path.join(HERE, 'fightcord.png'))

# the splash screen's logo (fightcade-fontstyle/splash-art.js): a WebP data URL inside a
# no-op plugin, so the in-app updater (which only ships .js) can deliver it too
import base64, io
buf = io.BytesIO()
full.resize((360, 360), Image.LANCZOS).save(buf, 'WEBP', quality=88, method=6)
art = 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode()
js = ('/** Fightcord splash art: the FightCord mascot logo (generated by fightcord/installer/make_icon.py). */\n'
      "module.exports = { id: 'splash-art', name: 'Splash art', start() {} };\nmodule.exports.ART = '" + art + "';\n")
open(os.path.join(HERE, '..', '..', 'fightcade-fontstyle', 'splash-art.js'), 'w', encoding='utf8', newline='\n').write(js)
print('splash-art.js written (%d KB)' % (len(js) // 1024))
print('logo.png and fightcord.ico written')
