#!/usr/bin/env node
/**
 * Writes the installer's translation tables (installer/i18n.json) into FightcordSetup.cs, between
 * the "i18n tables" markers. The .cs has to stay ASCII (Windows' C# 5 compiler reads it as ANSI),
 * so every non-ASCII character becomes a \uXXXX escape. build.ps1 runs this before compiling.
 *
 *   node installer/make_i18n.js          rewrite the tables
 *   node installer/make_i18n.js --check  fail when a string the .cs uses (L.T / L.F) has no translation
 */
'use strict';
const fs = require('fs');
const path = require('path');

const CS = path.join(__dirname, 'FightcordSetup.cs');
const JSON_FILE = path.join(__dirname, 'i18n.json');
const START = '    // ---- i18n tables (generated by installer/make_i18n.js from i18n.json; do not edit) ----';
const END = '    // ---- end i18n tables ----';

const lit = (s) => '"' + [...String(s)].map(ch => {
    if (ch === '\\') return '\\\\';
    if (ch === '"') return '\\"';
    if (ch === '\n') return '\\n';
    const c = ch.codePointAt(0);
    if (c >= 0x20 && c < 0x7f) return ch;
    if (c > 0xffff) { const h = Math.floor((c - 0x10000) / 0x400) + 0xd800, l = ((c - 0x10000) % 0x400) + 0xdc00; return '\\u' + h.toString(16) + '\\u' + l.toString(16); }
    return '\\u' + c.toString(16).padStart(4, '0');
}).join('') + '"';

// the strings the .cs asks for: L.T("...") / L.F("...", ...) -- C# escapes read back into text
function used(src) {
    const out = new Set();
    const re = /\bL\.[TF]\(\s*"((?:\\.|[^"\\])*)"/g;
    let m;
    while ((m = re.exec(src))) out.add(m[1].replace(/\\u([0-9a-fA-F]{4})/g, (x, h) => String.fromCharCode(parseInt(h, 16))).replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\'));
    // L.T(cond ? "a" : "b")
    const re2 = /\bL\.T\(\s*\w+\s*\?\s*"((?:\\.|[^"\\])*)"\s*:\s*"((?:\\.|[^"\\])*)"/g;
    while ((m = re2.exec(src))) { out.add(m[1]); out.add(m[2]); }
    return out;
}

const src = fs.readFileSync(CS, 'utf8');
const tables = JSON.parse(fs.readFileSync(JSON_FILE, 'utf8'));
const want = used(src);
let missing = 0;
for (const lang of Object.keys(tables)) {
    for (const k of want) if (!(k in tables[lang])) { console.log(lang + ' missing: ' + JSON.stringify(k)); missing++; }
    for (const k of Object.keys(tables[lang])) {
        const holes = (s) => (s.match(/\{\d+\}/g) || []).sort().join();
        if (holes(k) !== holes(tables[lang][k])) { console.log(lang + ' broken {n}: ' + JSON.stringify(k)); missing++; }
    }
}
if (process.argv.includes('--check')) process.exit(missing ? 1 : 0);

const body = [START, '    static partial class L', '    {'];
for (const lang of Object.keys(tables)) {
    const name = lang.charAt(0).toUpperCase() + lang.slice(1);
    body.push('        static readonly Dictionary<string, string> ' + name + ' = new Dictionary<string, string>', '        {');
    body.push(Object.keys(tables[lang]).map(k => '            { ' + lit(k) + ', ' + lit(tables[lang][k]) + ' }').join(',\n'));
    body.push('        };');
}
body.push('    }', END);

const nl = src.includes('\r\n') ? '\r\n' : '\n';
let out = src.replace(/\r\n/g, '\n');
const block = body.join('\n');
const a = out.indexOf(START), b = out.indexOf(END);
if (a >= 0 && b > a) out = out.slice(0, a) + block + out.slice(b + END.length);
else {
    // first time: before the namespace's closing brace
    const end = out.lastIndexOf('\n}');
    out = out.slice(0, end) + '\n\n' + block + out.slice(end);
}
if (/[^\x00-\x7f]/.test(out)) throw new Error('FightcordSetup.cs is not ASCII after the update');
fs.writeFileSync(CS, out.replace(/\n/g, nl));
console.log('installer tables: ' + Object.keys(tables).map(l => l + ' ' + Object.keys(tables[l]).length).join(', ') + (missing ? ' (' + missing + ' problems)' : ''));
process.exit(missing ? 1 : 0);
